### ISSUE TITLE
MLST giving incorrect alleles and ST

### ISSUE THREAD

**Issue by kwongj** [tseemann/mlst#11]
eg. Kpneumoniae ST258

```$ mlst /home/jkwong1/Kpneumo/KPC/fasta/2012-10753.fa --scheme kpneumoniae```
```$ mlst2 /home/jkwong1/Kpneumo/KPC/fasta/2012-10753.fa```

**Comment by tseemann** [comment]
I think you can trust mlst2 now, but mlst still needs some work. I've realised BLAT 'tsize' is not what I thought it was!

**Comment by kwongj** [comment]
Fixed #11
