### ISSUE TITLE
blastn usage reporting

### ISSUE THREAD

**Issue by mcroxen** [tseemann/mlst#110]
You may be interested in knowing this for your blast applications:

https://www.ncbi.nlm.nih.gov/books/NBK569851/#intro_Privacy.Optout_of_Usage_Reporting

**Comment by HBrendy** [comment]
Blast Usage Reporting caused the delay reported in #115 . Adding `export BLAST_USAGE_REPORT=false` fixed it. Thanks for the hint @mcroxen .

**Comment by andersgs** [comment]
Thank you both.
