### ISSUE TITLE
Failed to install latest version (v2.19.0) through conda

### ISSUE THREAD

**Issue by llk578496** [tseemann/mlst#112]
Hi,

I just tried to install the latest version (v2.19.0) through conda, but seems it fails and could only install older version (v2.11.0). May I know is there are way to install the latest version through conda?

> conda install -c conda-forge -c bioconda -c defaults mlst
> 
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: done
> 
>` ##Package Plan ##`
> 
>   environment location: /home/gilmansiu3/miniconda3
> 
>   added / updated specs:
>     - mlst
> 
> 
> The following packages will be downloaded:
> 
>     package                    |            build
>     ---------------------------|-----------------
>     mlst-2.11                  |                0        10.8 MB  bioconda
>     perl-moo-2.001000          |          pl526_2          42 KB  bioconda
>     ------------------------------------------------------------
>                                            Total:        10.9 MB
> 
> The following NEW packages will be INSTALLED:
> 
>   mlst               bioconda/linux-64::mlst-2.11-0
>   perl-bioperl       bioconda/linux-64::perl-bioperl-1.6.924-4
>   perl-class-method~ bioconda/linux-64::perl-class-method-modifiers-2.12-pl526_0
>   perl-devel-global~ bioconda/linux-64::perl-devel-globaldestruction-0.14-pl526_0
>   perl-module-runti~ bioconda/linux-64::perl-module-runtime-0.016-pl526_1
>   perl-moo           bioconda/linux-64::perl-moo-2.001000-pl526_2
>   perl-role-tiny     bioconda/noarch::perl-role-tiny-2.000008-pl526_0
>   perl-sub-exporter~ bioconda/linux-64::perl-sub-exporter-progressive-0.001013-pl526_0
>   perl-threaded      bioconda/linux-64::perl-threaded-5.26.0-0
>   perl-yaml          bioconda/noarch::perl-yaml-1.29-pl526_0
>   pip                conda-forge/noarch::pip-21.3.1-pyhd8ed1ab_0
>   wheel              conda-forge/noarch::wheel-0.37.0-pyhd8ed1ab_1
> 
> 
> Proceed ([y]/n)? n
> 
> 
> CondaSystemExit: Exiting.
>

**Comment by rpetit3** [comment]
Hi @llk578496 I wonder if this will work for you:
```
conda create -n mlst -c conda-forge -c bioconda -c defaults 'mlst=2.19.0'
conda activate mlst
mlst --version
```

**Comment by llk578496** [comment]
Hi @rpetit3 I used `mamba` because it seems to be faster and it works!

`mamba create -n mlst -c conda-forge -c bioconda -c defaults 'mlst=2.19.0'`

Thanks a lot!

**Comment by rpetit3** [comment]
`mamba` is the best! Glad you got it to work!
