### ISSUE TITLE
Issue with DB retrieval and dependancy

### ISSUE THREAD

**Issue by kimleeng** [tseemann/mlst#12]
Just updated to mlst 2.0, 
-First a minor detail was I had a dependancy for Moo.pm for my perl which I got around by cpan Moo. 
-Second, the scripts/mlst-download_pub_mlst puts the dbases.xml file into pubmlst but then doesn't look for dbases.xml in pubmlst but in the current working directory. Copying dbases.xml from pubmlst to current working directory is a workaround.
-Third the script generated from mlst-download_pub_mlst doesn't execute the download but prints it to terminal. Copying and pasting it is a workaround for this.
-Finally scripts/mlst-make_blast_db appears to be set up to be only run from the scripts folder (running /<somelocation>/mlst-2.0/scripts/mlst-make_blast_db won't work and it appears to be trying to add things improperly, looks like its assuming the wrong folder (db instead of db/pubmlst)
"Adding: db
cat: /home/kimn/software/mlst-2.0/scripts/../db/db/*.tfa: No such file or directory 
Adding: pubmlst
cat: /home/kimn/software/mlst-2.0/scripts/../db/pubmlst/*.tfa: No such file or directory 
Adding: blast
cat: /home/kimn/software/mlst-2.0/scripts/../db/blast/*.tfa: No such file or directory
Adding: species_scheme_map.tab
cat: /home/kimn/software/mlst-2.0/scripts/../db/species_scheme_map.tab/*.tfa: Not a directory"

Hope the information is useful.

**Comment by tseemann** [comment]
That script isn't really meant for others to use, it's more for me to update the master github one. May I ask why you are using it? I already provide all the databases.

It deliberately does not run the commands - it's so I can sanity check them first. You can just pipe the output of the command to "sh" and it will execute them all.

Yes, those scripts are meant to be run from where they are - as I said they aren't really meant for users to run yet, and I do not talk about them in the documentation. They are "hidden" in the scripts/ folder and not put in the bin/ or PATH.

I will use your feedback to improve those scripts in the future for general users to use. 

PubMLST often has bugs int he downloaded files that need to be corrected too, so it's not always straighforward to update.

Cheers!

**Comment by kimleeng** [comment]
I was checking them as down the line I had used them in the past to update my mlst database when they get updated. So in case we're looking at new CC types I'll be able to detect them off up to date data.
