### ISSUE TITLE
Typing O. tsutsugamushi and culling limit

### ISSUE THREAD

**Issue by embatty** [tseemann/mlst#13]
I'm having problems getting MLST to type some O. tsutsugamushi strains. I ran it on the two full reference strains, and on default parameters on the references it types 3/7 alleles (correctly). If I increase the culling limit to 40 it types 6/7 alleles. I can't get it to type the final allele (nrdF) even if I relax all the parameters, so I don't know what the problem is there. My guess is that the repetitive nature of the genomes is causing a problem with multiple overlapping hits and the culling limit - can it be raised, or have a command line option to raise it?

(The two references are ftp://ftp.ncbi.nlm.nih.gov/genomes/Bacteria/Orientia_tsutsugamushi_Boryong_uid61621/NC_009488.fna ftp://ftp.ncbi.nlm.nih.gov/genomes/Bacteria/Orientia_tsutsugamushi_Ikeda_uid58869/NC_010793.fna if you want to test this yourself.)

**Comment by embatty** [comment]
I did some further digging and it looks like the problem with typing nrdF is that the otsutsugamushi nrdF sequences are not in the blast database. If I add http://pubmlst.org/data/alleles/otsutsugamushi/nrdF.tfa to the database it works. nrdF used to be called nrdB, I assume something was screwed up by the name change.

**Comment by tseemann** [comment]
Liz @embatty 

Are you using a recent version of the software ?

I also encountered the he bug in pubMLST and Keith Jolley fixed it up, and I fixed this a while back: https://github.com/tseemann/mlst/commit/d1121b03000d56dc4868a2e535139fa43af42e11
