### ISSUE TITLE
blastn version 2.2.28 error

### ISSUE THREAD

**Issue by tintin42** [tseemann/mlst#14]
When using blastn 2.2.28+ the script fails to recognize a lot of alleles in the senterica scheme, especially in the sucA locus (haven't tested with other schemes). Changing blastn version to 2.3.0+ fixes this (haven't tested other blastn versions).

**Comment by tseemann** [comment]
@tintin42 that is a strange bug. We use 2.2.28+ and 2.2.29+ here (not 2.3.0+ yet) and do 100s of Salmonella a year.

Do you have any public assemblies I can access (eg. Genbank) to see what happens to me?

Are you using latest github version?

**Comment by tseemann** [comment]
No response, closing.
