### ISSUE TITLE
C.diff MLST broken: ST-# and mlst_clade(#)

### ISSUE THREAD

**Issue by chrisgulvik** [tseemann/mlst#15]
The individual variants for each locus are properly identified, but the actual ST-# is printed as '-' even though the variants correspond to an actual ST-#. The column 'mlst_clade' column is relatively new for PubMLST's database on C. diff, which might be causing the parsing issue. I noticed it also doesn't parse these values, and most ST-#s have a clade-# assigned according to http://pubmlst.org/perl/bigsdb/bigsdb.pl?db=pubmlst_cdifficile_seqdef&page=downloadProfiles&scheme_id=1 They also used to have 2 different MLST schemes and now just have 1 (which actually looks like the older one where RT027 is ST-1 rather than the 2nd/newer scheme which had RT027 as ST-3).

C. diff ribotype 027s are ST-1 according to the scheme currently available on PubMLST, so here's a quick way to see the error (grab a RT027/ST-1):

`mkdir Cdiff_MLST_test && cd Cdiff_MLST_test`
`wget ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000085225.1_ASM8522v1/GCF_000085225.1_ASM8522v1_genomic.fna.gz`
`gunzip GCF_000085225.1_ASM8522v1_genomic.fna.gz`
`mlst GCF_000085225.1_ASM8522v1_genomic.fna`
`cd ../ && rm -r Cdiff_MLST_test`

*Actual Stdout:*
GCF_000085225.1_ASM8522v1_genomic.fna	cdifficile	-	adk(1)	atpA(1)	dxr(1)	glyA(10)	recA(1)	sodA(3)	tpi(5)	mlst_clade(-)

*Expected Stdout:*
GCF_000085225.1_ASM8522v1_genomic.fna	cdifficile	**1**	adk(1)	atpA(1)	dxr(1)	glyA(10)	recA(1)	sodA(3)	tpi(5)	**mlst_clade(2)**

**Comment by tseemann** [comment]
@chrisgulvik I fixed this bug  last month, sorry I forgot to file it here!

https://github.com/tseemann/mlst/commit/61bf07053521a5641c1868b7765aea889b865042

You will need to update from github.
