### ISSUE TITLE
MLST priority in reporting partial matches

### ISSUE THREAD

**Issue by andersgs** [tseemann/mlst#16]
Hi Torst.

When no ST is identified across multiple schemes, the priority for reporting currently seems to favour one that has the most definite matches. This is probably ok in most cases. However, I have come across a situation where it would've been better to report the one with the most matches (partial or not). 

Anders.

**Comment by tseemann** [comment]
@andersgs Can you let me know the example that failed?

**Comment by tseemann** [comment]
Better matching behaviour now via 279c78680fcca1af1f076a6f4467b306f329e9cf
