### ISSUE TITLE
Species scheme map - can one use it to get the associated genus/species taxon?

### ISSUE THREAD

**Issue by VGalata** [tseemann/mlst#19]
Dear Torsten,

After completing the MLST analysis I wanted to have the taxa associated with the found MLST schemes and used the species scheme map (`db/species_scheme_map.tab`). However, it is not consistent with the schemes listed by the tool:

These are in the mapping list but are **not** listed by the tool:

```
bburgdorferi,bifidobacterium,campylobacter,cdifficile,cdifficile_2,cneoformans,ecoli,haemophilus,lcasei,legionella,pagglomerans,pfreudenreichii,pshigelloides
```

And these are listed by the tool but are **not** contained in the mapping list:

```
bhampsonii,bhenselae,borrelia,bsubtilis,cfreundii,cmaltaromaticum,hinfluenzae,kkingae,kseptempunctata,leptospira_3,mbovis,orhinotracheale,otsutsugamushi,plarvae,ranatipestifer,shaemolyticus,shominis,slugdunensis,sthermophilus_2,tenacibaculum,tvaginalis
```

I am not sure this is an "issue" of the tool and whether the mapping list is used somewhere. But since it is included and is really useful for fast taxon mapping, I though it might be worth reporting.

Used version: `mlst 2.5`

**Comment by tseemann** [comment]
That file was something I was planning to make use of for other applications like you suggest.

It is out of date because pubMLST changes every month or so, schemes removed, schemes added etc. Hard to keep up.

If you are able to help me with the *new* entries I will add them in.

**Comment by VGalata** [comment]
Ok. I created a [mapping table](http://pastebin.com/a1rmL38m) for the missing schemes.

Used reference: [PubMLST](http://pubmlst.org/data/)

**Comment by tseemann** [comment]
@VGalata sorry for the slow reply, but i've incorporated your changes now, and added a few fixes of my own.

The main change is that it is now called `scheme_species_map.tab` so it's easier for me to keep track of the 1-to-many relationships.

Thanks for helping!

**Comment by tseemann** [comment]
I've also added some documentation: https://github.com/tseemann/mlst#mapping-to-genusspecies
