### ISSUE TITLE
A. baumannii Pasteur scheme not in BLAST database

### ISSUE THREAD

**Issue by VGalata** [tseemann/mlst#20]
Dear Torsten,

It seems that the Pasteur *A. baumannii* scheme is not included in the BLAST database. Using the scheme `abaumannii_2` returns no results:

```
bin/mlst --scheme abaumannii_2 <input FASTA> --debug
```

Retuned (after skipping matches for the Oxford *A. baumannii* scheme):
```
$VAR1 = [
          'abaumannii_2',
          '-',
          '-/-/-/-/-/-/-'
        ];
```

Also the inspection of the BLAST database returned no matches for the genes from the Pasteur scheme.

```
blastdbcmd -db db/blast/mlst.fa -entry all | grep 'Pas_.*'
```

Used version: `mlst 2.5`

**Comment by tseemann** [comment]
@VGalata you are right - for some reason my script https://github.com/tseemann/mlst/blob/master/scripts/mlst-make_blast_db
does not include schemes with `_2` in them.

I suspect I had a good reason at the time but I am not sure why now!

I have fixed the problem. Thank you for the report. Please use the latest github version (git clone).
