### ISSUE TITLE
Update the schemes?

### ISSUE THREAD

**Issue by lskatz** [tseemann/mlst#21]
How does one update the schemes?  I feel like I am either missing that script or missed it in the documentation.

**Comment by lskatz** [comment]
Never mind.  Could you update the documentation to include `mlst-download_pub_mlst` or whatever the suggested workflow is?

**Comment by tseemann** [comment]
Updating the schemes often involves some manual work due to errors and renamings and scheme withdrawals that occur with PubMLST....

I need to make that script more robust, and/or incorporate it into the main tool.

**Comment by tseemann** [comment]
@lskatz I've added instructions here: https://github.com/tseemann/mlst#updating-the-database
