### ISSUE TITLE
Different runs report different schemes

### ISSUE THREAD

**Issue by miguelpmachado** [tseemann/mlst#23]
Hi,
I'm running MLST v2.5 (commit 8ddd963) on several assembly files and, using auto-detection mode, for two of them MLST either return sdygalactiae (which they should be) or streptomyces!
Is this normal or expected?
Thank you in advance.
Best regards,
Miguel

**Comment by tseemann** [comment]
@miguelpmachado MLST tries to return the best matching scheme, but if there are a lot of missing alleles, the scoring system I use is primitive!  I need to fix that.  Do you have an example?

**Comment by tseemann** [comment]
These edge cases are challenging. It's usually bad data which causes it, mixed cultures.

Some improvements via 279c78680fcca1af1f076a6f4467b306f329e9cf
