### ISSUE TITLE
Different MLSTs for a specie

### ISSUE THREAD

**Issue by MathGon** [tseemann/mlst#24]
Hi Torsten,

I'm interested by *Brucella* diversity, I managed to perform MLST analysis from WGS contigs with the [MLST9](http://pubmlst.org/perl/bigsdb/bigsdb.pl?db=pubmlst_brucella_seqdef). Unfortunately, I didn't managed to perform the analysis on the MLST21. Is there an option to select the other dataset?

Thanks

**Comment by tseemann** [comment]
@MathGon I do not understand what you mean?

MLST will automatically find everything that is in your dataset.
Maybe you don't really have MLST 21 ?
What does it say when you give it a MLST 21 contig set?

The ST21 alleles are in the database:
```
ST    gap     aroA    glk     dnaK    gyrB    trpE    cobQ    int_hyp omp25
21      1       6       4       1       5       3       5       4       5
```

Question - is the **Brucella** scheme really 9 genes?

**Comment by MathGon** [comment]
Excuse me, my question wasn't very clear. 

For *Brucella*, there's is two schemes: one with 9 loci and a second with 21 loci. I manage to perform analysis with the 9 loci dataset but how to perform this analysis with the 21 loci?

**Comment by tseemann** [comment]
@MathGon you are right, there is multiple schemes. In fact, BigsDB has so many different schemes for each taxon, include rMLST and other ones.  

I am only supporting the 'traditional' schemes with < 10 genes.

There are the ones downloaded via https://pubmlst.org/data/dbases.xml

I will consider adding different schemes in the future.
