### ISSUE TITLE
Path to BLAST

### ISSUE THREAD

**Issue by malik010** [tseemann/mlst#27]
Hi Torsten,

I have installed MLST successfully and tested the following command "% mlst --list", which works.
However, I am wondering which file I need to tweak to setup the PATH to BLAST so that I can do my analysis. I already have ncbi-blast-2.5.0+ installed on my system.

Any help will be highly appreciated.
Thanks and best regards,
Adeel

**Comment by tseemann** [comment]
All it needs is `blastn` to be in your PATH.  If BLAST+ is installed in your system it should just work.

What does it say if you type `blastn -help` ?

**Comment by malik010** [comment]
It works now. I rebooted the system after adding the PATH to blast.
Thanks.
