### ISSUE TITLE
Harmonise output between `discovery of scheme mode`, and `forced scheme mode`

### ISSUE THREAD

**Issue by andersgs** [tseemann/mlst#32]
Currently, the default mode, where MLST attempts to discover the MLST scheme from the data has a differently formatted output from when using the `--scheme` option.

It would be nice if they were the same.

**Comment by tseemann** [comment]
This is for backward compatibility with mlst 1.x, but yes it is a problem.

I plan to add a `--legacy` mode.

**Comment by tseemann** [comment]
Ok, now the new output is used whether or not you supply `--scheme`.

To get the old output, you must supply `--legacy` and `--scheme`.
