### ISSUE TITLE
No longer outputs header line.

### ISSUE THREAD

**Issue by andersgs** [tseemann/mlst#37]
Unless using the `--legacy` no header line is outputted any longer. The line is useful when parsing the fields in a pipeline, and protects against changes in the order of the fields. Maybe add a `--no-header` option to suppress it.

**Comment by tseemann** [comment]
The non-legacy mode of `mlst` never output a header, because the number of alleles could be different for each row due to different schemes.

However the documentation is wrong, and I will fix that.
