### ISSUE TITLE
How Can I return to the old version?

### ISSUE THREAD

**Issue by lancetxiao** [tseemann/mlst#40]
I am using the mlst version 2.8. but when I "mlst" just one gene ( PCR one gene and sequencing) , this version show no result(in the pic  result  - -), but the old version can give the result of this gene. for example adk(3).
SO I WANT THE VERSION 2.6. How Can I return to the old version? Thanks a lot.
<img width="378" alt="default" src="https://user-images.githubusercontent.com/21260389/29872881-f7dbd404-8dc3-11e7-88b0-2e287bdfe722.png">

**Comment by tseemann** [comment]
I'm not quite sure what you are saying happened. Can you provide me with the exact sequence file you gave to `mlst` ?   I see it says `exact match found` but your screenshot is clipped off?

All old releases of `mlst` are here:
https://github.com/tseemann/mlst/releases

You may want to try 2.9 just in case there was a bug in 2.8.  MLST schemes also change all the time. Some allelles are deleted.

**Comment by lancetxiao** [comment]
I am sorry not make the problem clear. In The version 2.6， when I “mlst”   one gene， IT result like this in the picture. SO I can save the result to a text.  However the version 2.8 JUST show the exact match found, I cannot save it. 
<img width="673" alt="default" src="https://user-images.githubusercontent.com/21260389/29904119-df6e65d2-8e39-11e7-9971-96f24142f634.png">

**Comment by tseemann** [comment]
@lancetxiao the red arrow is pointing to an empty?  are you saying, that in version 2.6, the *DNA sequence* was where that black empty space is?

**Comment by lancetxiao** [comment]
The Version 2.8
<img width="751" alt="default" src="https://user-images.githubusercontent.com/21260389/29995224-24c1b10a-9017-11e7-9fc5-4b99ed51fd99.png">
The Version 2.6
<img width="1341" alt="default" src="https://user-images.githubusercontent.com/21260389/29995225-3e14a0fe-9017-11e7-8c07-c8ec987cf15e.png">

So I can save The result of the version 2.6 by “$  mlst *.fasta >mlst_reslut".

**Comment by andrewjpage** [comment]
Could you provide the sequence?
