### ISSUE TITLE
Homebrew-Science is now deprecated and the repository is archived to read only mode

### ISSUE THREAD

**Issue by jemueller** [tseemann/mlst#47]
The described method of installation for MLST is still listed as using homebrew-science, however this repository has been deprecated and marked as archived because:

"This tap was deprecated because it had different goals from the wider Homebrew organisation (e.g. Linuxbrew CI/support). All widely used, buildable formulae were migrated to homebrew/core."

MLST has not been migrated over to homebrew/core yet as far as I can tell from looking at their current list of migrated formulas:

https://github.com/Homebrew/homebrew-science/blob/master/tap_migrations.json

I was wondering if MLST was going to be migrated to homebrew/core and what the timetable for this was or if there was another preferred way of installing it instead of this (and until this migration can take place).

Any help you can offer would be greatly appreciated. Thank you.

**Comment by tseemann** [comment]
@jemueller You can still  use i - it has just moved:

```
brew tap brewsci/science 
brew tap brewsci/bio
brew untap homebrew/science
```

Getting into `homebrew/core` is difficult due to the Perl module directive being deprecated too :(

One solution is to switch to Bioconda instead.
