### ISSUE TITLE
ST not displayed

### ISSUE THREAD

**Issue by rodsa** [tseemann/mlst#5]
When I run the script I get the following:

Use of uninitialized value in join or string at ./mlst line 160, <TSV> line 123.
Use of uninitialized value in join or string at ./mlst line 160, <TSV> line 178.
Use of uninitialized value in join or string at ./mlst line 160, <TSV> line 179.
Use of uninitialized value in join or string at ./mlst line 160, <TSV> line 180.
Use of uninitialized value in join or string at ./mlst line 160, <TSV> line 181.
Use of uninitialized value in join or string at ./mlst line 160, <TSV> line 182.
Use of uninitialized value in join or string at ./mlst line 160, <TSV> line 201.
Use of uninitialized value in join or string at ./mlst line 160, <TSV> line 203.
Use of uninitialized value in join or string at ./mlst line 160, <TSV> line 205.
Use of uninitialized value in join or string at ./mlst line 160, <TSV> line 207.
Use of uninitialized value in join or string at ./mlst line 160, <TSV> line 211.
Use of uninitialized value in join or string at ./mlst line 160, <TSV> line 212.

The combination of alleles obtained for the sequence is indeed present in the species.tfa file, but instead of showing the corresponding ST a hyphen is displayed

**Comment by tseemann** [comment]
@rodsa - can you send me the .fasta file and what --scheme you were using?

**Comment by rodsa** [comment]
Thanks for your reply. Here the .fasta file. Scheme = difficile
Cheers
César

**Comment by tseemann** [comment]
Where is the FASTA file? You can email it to torsten.seemann@gmail.com

**Comment by tseemann** [comment]
@rodsa I've solved the problem! It was only affecting 'cdifficile'. The PubMLST data has a "mlst_clade" column I have never seen before, most have "clonal_complex". I will make a new 1.2 release with this fixed.

I appreciate the time you took to send me the test data file, it was very kind of you.

PS. Your contigs are ST35 :-)
```cdifficile	35	2	5	8	1	1	3	6```

**Comment by rodsa** [comment]
It´s working now! Great, thanks for your efforts. 
I know you have been working with Cdif before, I have a bunch of Cdif genomes to play with, just in case you are interested!
Regards 
César
