### ISSUE TITLE
IUPAC codes and DSTs

### ISSUE THREAD

**Issue by mdhitch** [tseemann/mlst#52]
I seem to be having an issue retrieving matching alleles when using the _Candida_ _albicans_ database when sequences are containing IUPAC codes (for diploid sequence types). For example I can take the SYA1_43 allele and when using mlst I only get alleles that are similar but never SYA1_43 (routinely get (SYA1_192). I have tried to adjust --minid, --mincov and --minscore independently and together (each to 100) but then get no hits. 

I have updated the database, and have checked that allele SYA1_43 is present (which it is). I can see that you have included the line "Ideally the sequences will not contain any ambiguous IUPAC symbols. i.e. just A,T,C,G." in README but of course for DST then we need IUPAC symbols.

Do you have any ideas of a work around?

Many thanks

Matt

**Comment by tseemann** [comment]
@mdhitch I think I've been forgetting to filter out the Fungi schemes.  `mlst` will probably never be able to support the ambiguous IUPAC symbols, sorry :-(
