### ISSUE TITLE
Handling pstS(-) allele in E.faecium

### ISSUE THREAD

**Issue by tseemann** [tseemann/mlst#59]
A totally missing allele can be `0` .................

**Comment by andersgs** [comment]
Here is an odd thing, which I am not sure is intended or not... But, the current version does assign  the correct STto isolates with a missing `pstS` allele:

```
contigs.fa  efaecium        1424    atpA(9) ddl(1)  gdh(1)  purK(1) gyd(12) pstS(-) adk(1)
```
But, it doesn't label it correctly (i.e., `pstS(0)`). 

Is that what this issue is about?

**Comment by tseemann** [comment]
To be honest I have no idea why this works!

**Comment by tseemann** [comment]
As I excpected, it works due to Perl's notion of true/false working in our favour.
```
    my $sig = join "/", map { $col[$_] || '-' } (1 .. @gene);
```
The `col[ ]` is the allele ID int the .txt file, which is 0 for the null allelle.
As this is false, the `|| '-'` converts it into `-`.
This makes a string signtaure for ST1424 with a `-` in it.
Later on, when we get `-`, it finds a signature match.
I just need to change the output to 0 i guess!

**Comment by tseemann** [comment]
Ok i have fixed this.
It will now print 0 if the allele is - but the signature gets a valid ST type
This also gains it 13 points in the scoring systen, bringing total to 100 now.
