### ISSUE TITLE
rmlst error "Can't use an undefined value as a HASH reference at /anaconda/bin/../perl5/MLST/Scheme.pm line 65"

### ISSUE THREAD

**Issue by Walwa** [tseemann/mlst#72]
Hi, and thanks for the great software.
I downloaded the latest version 2.15.1 through Anaconda, and added a rmlst database from pubmlst with a file containing the profiles. Then I ran your script mlst-make_blast_db. When I run mlst I get an output in the screen attributing sequences to loci and alleles but then it finishes with "Can't use an undefined value as a HASH reference at /anaconda/bin/../perl5/MLST/Scheme.pm line 65." I have tried to get the output to write to a file and that doesn't work either. 
Do you have any suggestions?

**Comment by tseemann** [comment]
I can only assume the files were not formatted in the correct manner?
Did they have Unix line endings?

**Comment by Walwa** [comment]
Thank you for your advise. Sorry for the delay in reply. Yes I did this on a Mac and there were line endings.

**Comment by tseemann** [comment]
`mac2unix` or `dos2unix` are my friends

**Comment by Walwa** [comment]
Thank you.

I will use these in the future.

**Comment by jmarshallnz** [comment]
I'm having the same problem with mlst 2.18.1 from miniconda. Two lots of errors:

readline() on closed filehandle $fh at /home/jcmarsha/miniconda3/bin/../perl5/MLST/Scheme.pm line 38.
Use of uninitialized value $header in scalar chomp at /home/jcmarsha/miniconda3/bin/../perl5/MLST/Scheme.pm line 39.
Use of uninitialized value $header in split at /home/jcmarsha/miniconda3/bin/../perl5/MLST/Scheme.pm line 40.

Then a bunch of exact allele match calls, then:

readline() on closed filehandle $fh at /home/jcmarsha/miniconda3/bin/../perl5/MLST/Scheme.pm line 53.
Can't use an undefined value as a HASH reference at /home/jcmarsha/miniconda3/bin/../perl5/MLST/Scheme.pm line 65.

The .fa files all have unix line endings, as do the files used for the campy_cgmlst blast database build. BUT, we don't get the same errors with the campylobacter database. Thus, my conclusion is some issues with the generation of the blast database?

Is there anything I can do to troubleshoot this? Thanks!

**Comment by tseemann** [comment]
The files need to be `.tfa` not `.fa`
The scheme name must be the same as the folder name.  eg.  `campy/campy.txt`

**Comment by jmarshallnz** [comment]
Thanks for the quick reply! Problem was the scheme name (had an extra .txt on the end of it).

The mlst-make_blast_db completed without errors in both cases.

All good now thanks! :)
