### ISSUE TITLE
Extracting allelle sequence information from sample whole genome 

### ISSUE THREAD

**Issue by Nits11** [tseemann/mlst#73]
Hi Torsten,

Does this program can also generate an output file of MLST allele sequences for the sample sequences?
 I guess during the process of sequences alignment for allele type search, program finds an alignment hit in the sample sequence with one of target gene scheme sequences in the database. I want to use the allelic sequence from the sample. Will it be possible to tweak the tool or to use any existing option so that we can also have 7 gene allele sequences extracted from the sample genome being analyzed.
Looking forward for your valuable suggestion.
Thanks

**Comment by tseemann** [comment]
There is a `--novel OUTFILE` option - does that do what you want?

**Comment by Ivalize** [comment]
Hi.

I have the same question.
How to generate a fasta sequence file with the allelic detection (output file with the sequence aligned) ?.

Thanks.

**Comment by tseemann** [comment]
@Ivalize sequence aligned to what?
