### ISSUE TITLE
Update list of Eukaryotic schemes.

### ISSUE THREAD

**Issue by andersgs** [tseemann/mlst#74]
I am seeing a few Eukaryotic schemes leaking through.

Current list should include all of these:
```
'afumigatus'
'blastocystis'
'calbicans'
'cglabrata'
'ckrusei'
'ctropicalis'
'csinensis'
'kseptempunctata'
'sparasitica'
'tvaginalis'
```

**Comment by tseemann** [comment]
Thanks for the updated list.
I currently only had `{tvaginalis,ckrusei,ctropicalis,calbicans,sparasitica}`

**Comment by tseemann** [comment]
Tagged 2.16.1
