### ISSUE TITLE
[15:00:59] Could not find 'file'. Please install it and ensure it is in the PATH.

### ISSUE THREAD

**Issue by aschuerch** [tseemann/mlst#79]
It seems that some requirement is missing from the conda recipe that I am using to install mlst=2.10. I'd like to fix it but have no clue which requirement it could be. Any hint for me? Thanks!

**Comment by aschuerch** [comment]
I fixed it by updating to the latest version

**Comment by tseemann** [comment]
I will be replacing that with any2fasta soon.
