### ISSUE TITLE
Latest mlst database includes a new column 

### ISSUE THREAD

**Issue by kimleeng** [tseemann/mlst#8]
The latest mlst database includes a new column for species which if not removed will cause the type to not be identified properly and will search for a nonexistant species.tsv.

**Comment by tseemann** [comment]
@kimleeng i'm not sure what you mean? can you point to a URL of a file you have?

**Comment by kimleeng** [comment]
So using mlst v1.2 / sbin / run_me to obtain the mlst public db (on oct 26, 2015) the abaumannii scheme there is a column called "species" and running /mlst/bin/mlst --scheme abaumannii *.fasta gives many of these errors "Use of uninitialized value in join or string at /software/mlst-1.2/bin/mlst line 162, <TSV> line 2." I can get rid of this error by removing the extra "species" column.

Here's the head of the file abaumannii.txt:

ST	Oxf_gltA	Oxf_gyrB	Oxf_gdhB	Oxf_recA	Oxf_cpn60	Oxf_gpi	Oxf_rpoD	clonal_complex	species
1	1	1	1	1	1	1	6		
2	2	2	2	1	1	2	7		
3	1	1	1	1	2	1	4		
4	1	12	3	2	2	7	3		
5	1	3	3	2	2	3	1		
6	1	4	3	2	2	3	3		
7	3	3	3	2	3	3	8		
8	4	4	4	4	4	5	9		
9	1	3	3	2	2	6	8

Hope the information helps.

**Comment by tseemann** [comment]
@kimleeng - that helped a lot!  I have fixed the bug. I will make a new release. Thank you for your patience.
