### ISSUE TITLE
New Scheme error

### ISSUE THREAD

**Issue by Merguerrero** [tseemann/mlst#80]
I'm not able to create a new scheme, when  `mlst --longlist | grep pj`  got this error: 

```
readline() on closed filehandle $fh at ~/mlst/bin/../perl5/MLST/Scheme.pm line 38.
Use of uninitialized value $header in scalar chomp at ~/mlst/bin/../perl5/MLST/Scheme.pm line 39.
Use of uninitialized value $header in split at ~/mlst/bin/../perl5/MLST/Scheme.pm line 40.
```
Any clue?

Thanks in advance!

**Comment by tseemann** [comment]
1. what do you mean "create new scheme" ?
2. how did you install mlst?
3. what does `mlst --version` say?

**Comment by Merguerrero** [comment]
1. what do you mean "create new scheme" ?
I would like to add a new scheme, and I followed the guidelines in [Adding a new scheme](https://github.com/tseemann/mlst#adding-a-new-scheme) secion
2. how did you install mlst?
I cloned from git hub.
3. what does mlst --version say?
mlst 2.16.2

**Comment by tseemann** [comment]
please can you tell me what this command says
```
ls -lsa /path/to/mlst/db/pubmlst/yourscheme/
```

**Comment by eneasdecarvalho** [comment]
Hi. It happened to me. I just fixed it renaming the .txt scheme file (which I had named as DownloadedScheme_organism.txt) to the same name of the scheme (then just scheme.txt)

Although, in the guidelines, the filename has the same name of the scheme, this is not highlighted as essencial, and I did not notice it. Maybe it could be highlighted in the guidelines.

**Comment by tseemann** [comment]
@eneasdecarvalho thank you - i have updated the documentation to make it clear that SCHEME (folder) must match (SCHEME.txt) filename.
