### ISSUE TITLE
Retrieving new alleles in the correct orientation

### ISSUE THREAD

**Issue by ramirma** [tseemann/mlst#86]
Thank you for a great tool and a great response time on the issues.
This is more of a feature request than an issue. Depending on the original contig orientation in the assembly, occasionally the sequence of the novel alleles is the reverse complement of the pubmlst sequence and the DB complains about it requiring an extra step. It would be ideal if mlst would already write the novel allele file in the correct orientation.

**Comment by tseemann** [comment]
@ramirma let me know if this doesn't work. i will make a release soon.
