### ISSUE TITLE
NG-MAST

### ISSUE THREAD

**Issue by rstabler** [tseemann/mlst#9]
Hi

NG-MAST doesn't work as the scheme is a tad of a mess (IMHO)!
If you run verbose method you will see multiple perfect hits to a single strains and 'mlst' just takes the last in the list - which is not right mostly.

**Comment by tseemann** [comment]
@rstabler - thank you for the feedback on ng_mast.  this scheme was new to me, and it appeared 'mlst' like so I retrofitted it. but i hadn't considered multi-hits. are the ng_mast genes duplicated in the genome? are you saying there could be multiple 'correct' ng_mast types for a single genome? am meant to choose the pair that has a type number?  if so, "tad of a mess" is being polite ;-)

**Comment by rstabler** [comment]
Hi Torsten

Yes, 'alleles' overlap but staggered so you (can but not always) get multiple hits for 1 or both genes so if you get 2 x por and 4 x tbpb that is 8 possible NG-MAST types at the same time!
Yes, I was being polite......

However if you look at the NG MAST definition many of the alleles don't have the correct conserved start sequence (why are they alleles then!!!???). I have not worked with this scheme doing it the old fashioned Sanger method as they use diagnostically so perhaps I am missing something. All I know is that for NGS is a shambles.

Regards

Richard


Richard Stabler Ph.D.
Senior Lecturer in Molecular Bacteriology
Dept of Pathogen Molecular Biology
Faculty of Infectious & Tropical Diseases
London School of Hygiene and Tropical Medicine
Tel +44 207 927 2824
Fax +44 207 927 2131
>>> Torsten Seemann <notifications@github.com> 03/08/15 11:48 PM >>>
@rstabler - thank you for the feedback on ng_mast.  this scheme was new to me, and it appeared 'mlst' like so I retrofitted it. but i hadn't considered multi-hits. are the ng_mast genes duplicated in the genome? are you saying there could be multiple 'correct' ng_mast types for a single genome? am meant to choose the pair that has a type number?  if so, "tad of a mess" is being polite ;-)


---

**Comment by tseemann** [comment]
I have removed NG-MAST from this tool as you are correct in that it needs more than just simple amplicon matching. 

We have written NG-MASTER instead: https://github.com/MDU-PHL/ngmaster

**Comment by rstabler** [comment]
Dear Torsten

That's great.

However I get this........

richard:/usr/local/bin/ngmaster-master$ ./ngmaster.py example.fna
ID    NG-MAST    POR    TBPB
Traceback (most recent call last):
   File "./ngmaster.py", line 101, in <module>
     proc = subprocess.Popen(['isPcr', f, 'stdin', 'stdout', 
'-tileSize=6', '-minPerfect=5', '-stepSize=3', '-maxSize=900'], 
stdin=subprocess.PIPE, stdout=subprocess.PIPE)
   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
     errread, errwrite)
   File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
     raise child_exception
OSError: [Errno 2] No such file or directory

As a non-python person I don't understand this if it's an easy 
fix/something I have done.

Regards

Richard

On 24/10/15 00:14, Torsten Seemann wrote:
>
> I have removed NG-MAST from this tool as you are correct in that it 
> needs more than just simple amplicon matching.
>
> We have written NG-MASTER instead: https://github.com/MDU-PHL/ngmaster
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/tseemann/mlst/issues/9#issuecomment-150713623>.
>

-- 
Richard Stabler Ph.D.
Senior Lecturer in Molecular Bacteriology
Dept of Pathogen Molecular Biology
Faculty of Infectious & Tropical Diseases
London School of Hygiene and Tropical Medicine
Tel +44 207 927 2824
Fax +44 207 927 2131
