### ISSUE TITLE
Multiple but same allele assigned

### ISSUE THREAD

**Issue by ramay** [tseemann/mlst#96]
Hi,
I am new to bacterial genomes and have a few questions on how to interpret the results from MLST.

1. For a contig, I got these results:
ref.fa	suberis	-	arcC(1)	ddl(1)	gki(1)	recP(1,1)	tdk(1)	tpi(1)	yqiL(1)

The two alleles found for recP are the same but it is not assigning an ST because of this. The ST in case one allele was found would be 1. Could I assume that ST is 1 in this case also?

2. Also for a  lot of my suberis genomes, no ST is assigned because that combination of alleles is not present in mlst database. Is there something else I can do to somehow group or identify these genomes?  I have used the nullarbor pipeline and found very few resistomes and virulomes also. 

Thanks a lot in advance!

Hena

**Comment by tseemann** [comment]
1. your isolate has two copies of recP for some reason, and  they are the same. this could be an assembly artifact or a real gene duplication. you should tell the curator of the suberis scheme.

2. you should send the alleles to the suberis curator so they can add them to the scheme. i am considering adding a special code for new alleles when you run multiple FASTA files at once but that won't occur soon.  Make try `chewBBACA` or other tools which can do this.

**Comment by ramay** [comment]
Thanks @tseemann ! I will contact the suberis curator.
Hena
