### ISSUE TITLE
Does not detect allele if it´s present in reverse orientation?

### ISSUE THREAD

**Issue by mdiricks** [tseemann/mlst#97]
I have samples for which I don´t get a valid allele call although I know the allele is present in one of the contigs (I give a multifasta file as input), but in reverse complement.
Does this script not take into account reverse complement sequences?

**Comment by mdiricks** [comment]
It does detect sequences in reverse orientation.
I got results for my sample only if I indicate the scheme in the command

**Comment by tseemann** [comment]
You can run with `--verbose` to see more info.

I am guessing you aren't reaching --minscore to report the matches in auto mode?

**Comment by mdiricks** [comment]
Thanks for your answer! 
verbose is an unknown function? 
Must be indeed that I don`t reach --minscore somehow. Haemophilus is genetically quite diverse, so could be due to that

**Comment by tseemann** [comment]
sorry wrong name:

  --debug           Verbose debug output to stderr (default OFF)
